

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Jx1912..
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://120.25.208.32:3306/kindergaten_db?serverTimezone=UTC&characterEncoding=utf-8&useSSL=false


mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:sqlMapConfig.xml


server:
  port: 8080
